# 测试样例2，心理咨询师

step welcome:
    speak "我是心里咨熊师完颜慧德，你有什么要问的吗？";
    listen 5, 20;
    branch "闺蜜", guimidimi;
    branch "我老公喜欢上了我妈妈", lonely;
    branch "华为手机", iphone;
    branch "没有穿好", gongchuqi;
    branch "读书有什么用吗", duoshu;
    default xiaoyongle;

step continue:
    speak "还有什么要问的吗？";
    listen 5, 20;
    branch "闺蜜", guimidimi;
    branch "我老公喜欢上了我妈妈", lonely;
    branch "华为手机", iphone;
    branch "没有穿好", gongchuqi;
    branch "读书有什么用吗", duoshu;
    branch "没", end;
    silence continue;
    default xiaoyongle;

step guimidimi:
    speak "好嘞，是闺咪，不好嘞，是敌咪。"
        + "什么是敌咪？敌人的秘密就叫敌蜜";
    silence continue;

step lonely:
    speak "这就不对啊，这是一个lonely的问题。"
        + "在这个过程中你要去跟你的妈妈谈，同时要跟你的老公去谈。"
        + "如果说谈不脱，就要想进一步的办法。";
    silence continue;

step iphone:
    speak "啊？本来我们说的是安分守己，安分守己你怎么又提到手机了呢？";
    silence continue;

step gongchuqi:
    speak "你们又在这里带什么节奏！供出去！你还待在这里干嘛？供出去！\n"
        + "每天总有这些黑粉来捣乱，我从来一般不发火，太不像话了真的是！";
    silence continue;

step duoshu:
    speak "duo书的拟人最美丽，duo书的拟人最优秀，duo书的拟人最通情达理。";
    silence continue;

step xiaoyongle:
    speak "你这问的什么问题？你把人笑拥了我跟你说";
    silence continue;

step end:
    speak "没问题了就供出去";
    exit;
